#!/usr/bin/env python3
"""
Pepper hold/reservoir sweep cell: HOLD=73, RESERVOIR=7.

Auto-generated by scripts/generate_hold_reservoir_grid.py — do not edit by
hand; regenerate instead.
"""
from __future__ import annotations

import json
import math
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

try:
    from datamodel import Order, OrderDepth, TradingState
except ImportError:
    @dataclass
    class Order:
        symbol: str
        price: int
        quantity: int

    @dataclass
    class OrderDepth:
        buy_orders: Dict[int, int] = field(default_factory=dict)
        sell_orders: Dict[int, int] = field(default_factory=dict)

    @dataclass
    class TradingState:
        traderData: str = ""
        timestamp: int = 0
        order_depths: Dict[str, OrderDepth] = field(default_factory=dict)
        position: Dict[str, int] = field(default_factory=dict)


POSITION_LIMITS: Dict[str, int] = {
    "ASH_COATED_OSMIUM": 80,
    "INTARIAN_PEPPER_ROOT": 80,
}

OSMIUM_FAIR_VALUE = 10_000
OSMIUM_MAX_BID = 9_999
OSMIUM_MIN_ASK = 10_001
OSMIUM_QUOTE_SIZE = 80

# --- Pepper hold / reservoir cell --------------------------------------
PEPPER_HOLD = 73                 # permanent long floor (drift capture)
PEPPER_RESERVOIR = 7       # extra capacity used for MM on top of the hold
PEPPER_MAX_POSITION = PEPPER_HOLD + PEPPER_RESERVOIR
# -----------------------------------------------------------------------

PEPPER_SLOPE = 0.001                 # mean +1 per 1000 timestamp units
PEPPER_MM_OFFSET = 2                 # penny2-style offset from best quote
PEPPER_EDGE_OFFSET = 3               # widen one extra tick at the band edges


@dataclass
class OrderBuilder:
    product: str
    position: int
    limit: int
    orders: List[Order] = field(default_factory=list)
    buy_used: int = 0
    sell_used: int = 0

    @property
    def buy_capacity(self) -> int:
        return max(0, self.limit - self.position - self.buy_used)

    @property
    def sell_capacity(self) -> int:
        return max(0, self.limit + self.position - self.sell_used)

    def add_buy(self, price: int, quantity: int) -> None:
        quantity = min(quantity, self.buy_capacity)
        if quantity > 0:
            self.orders.append(Order(self.product, int(price), int(quantity)))
            self.buy_used += quantity

    def add_sell(self, price: int, quantity: int) -> None:
        quantity = min(quantity, self.sell_capacity)
        if quantity > 0:
            self.orders.append(Order(self.product, int(price), int(-quantity)))
            self.sell_used += quantity


def best_bid_ask(order_depth: OrderDepth) -> Optional[Tuple[int, int]]:
    if not order_depth.buy_orders or not order_depth.sell_orders:
        return None
    return max(order_depth.buy_orders), min(order_depth.sell_orders)


class Trader:
    def run(self, state: TradingState):
        result: Dict[str, List[Order]] = {}
        saved = {}
        if state.traderData:
            try:
                saved = json.loads(state.traderData)
            except json.JSONDecodeError:
                pass

        for product, order_depth in state.order_depths.items():
            position = state.position.get(product, 0)
            limit = POSITION_LIMITS.get(product, 80)
            builder = OrderBuilder(product, position, limit)

            if product == "ASH_COATED_OSMIUM":
                for ask_price in sorted(order_depth.sell_orders.keys()):
                    if ask_price >= OSMIUM_FAIR_VALUE:
                        break
                    builder.add_buy(ask_price, abs(order_depth.sell_orders[ask_price]))

                for bid_price in sorted(order_depth.buy_orders.keys(), reverse=True):
                    if bid_price <= OSMIUM_FAIR_VALUE:
                        break
                    builder.add_sell(bid_price, abs(order_depth.buy_orders[bid_price]))

                bba = best_bid_ask(order_depth)
                if bba:
                    bot_bid, bot_ask = bba
                    bid_price = min(bot_bid + 1, OSMIUM_MAX_BID)
                    ask_price = max(bot_ask - 1, OSMIUM_MIN_ASK)
                else:
                    bid_price = OSMIUM_MAX_BID
                    ask_price = OSMIUM_MIN_ASK

                builder.add_buy(bid_price, OSMIUM_QUOTE_SIZE)
                builder.add_sell(ask_price, OSMIUM_QUOTE_SIZE)

            elif product == "INTARIAN_PEPPER_ROOT":
                # Phase 1: ramp up to the hold floor as quickly as possible.
                if position < PEPPER_HOLD and order_depth.sell_orders:
                    deficit = PEPPER_HOLD - position
                    builder.add_buy(min(order_depth.sell_orders), deficit)
                elif position < PEPPER_HOLD and order_depth.buy_orders:
                    deficit = PEPPER_HOLD - position
                    builder.add_buy(max(order_depth.buy_orders) + 1, deficit)

                # Phase 2: MM with the reservoir on top of the hold.
                if PEPPER_RESERVOIR > 0:
                    bba = best_bid_ask(order_depth)
                    if bba:
                        bot_bid, bot_ask = bba
                        mid = (bot_bid + bot_ask) / 2
                        timestamp = state.timestamp

                        # Rolling fair-value estimate: running mean of (mid - slope*t).
                        n = saved.get("pepper_n", 0) + 1
                        s = saved.get("pepper_sum", 0.0)
                        s += mid - PEPPER_SLOPE * timestamp
                        saved["pepper_n"] = n
                        saved["pepper_sum"] = s
                        intercept = s / n
                        fair_value = intercept + PEPPER_SLOPE * timestamp

                        max_bid = math.ceil(fair_value) - 1
                        min_ask = math.floor(fair_value) + 1

                        bid_offset = (
                            PEPPER_EDGE_OFFSET
                            if position <= PEPPER_HOLD + 1
                            else PEPPER_MM_OFFSET
                        )
                        ask_offset = (
                            PEPPER_EDGE_OFFSET
                            if position >= PEPPER_MAX_POSITION - 1
                            else PEPPER_MM_OFFSET
                        )

                        bid_price = min(bot_bid + bid_offset, max_bid)
                        ask_price = max(bot_ask - ask_offset, min_ask)

                        # Buy only while we're below the top of the band.
                        buy_room = max(0, PEPPER_MAX_POSITION - position)
                        if buy_room > 0:
                            builder.add_buy(bid_price, min(PEPPER_RESERVOIR, buy_room))

                        # Sell only above the hold floor — never dip into the core.
                        sell_room = max(0, position - PEPPER_HOLD)
                        if sell_room > 0:
                            builder.add_sell(ask_price, min(PEPPER_RESERVOIR, sell_room))

            result[product] = builder.orders

        return result, 0, json.dumps(saved)
