#!/usr/bin/env python3
"""
Generate a grid of self-contained bot files that sweep how much pepper
position is held as a permanent long (drift capture) vs. how much is left
as a reservoir for market making.

For each cell (H, R) with H + R <= 80, R >= 1 (or R == 0 for the pure-hold
baseline) we emit grid/hold_reservoir/h{H:02d}_r{R:02d}.py — a single file
you can upload directly to the IMC Prosperity website backtester.

Osmium logic is identical to round1bot.py (full-capacity penny MM + arb).
Pepper logic is round1bot.py's logic but parameterized:
  - market buy up to PEPPER_HOLD (core long, earns drift all round)
  - MM with PEPPER_RESERVOIR extra capacity on top:
      * buy side only fires while position < PEPPER_HOLD + PEPPER_RESERVOIR
      * sell side only fires while position >  PEPPER_HOLD (never breaks the floor)
"""
from __future__ import annotations

import argparse
import csv
from pathlib import Path
from textwrap import dedent

DEFAULT_STEP = 20
POSITION_LIMIT = 80


def parse_values(raw: str | None, step: int) -> list[int]:
    if raw:
        return sorted({int(x) for x in raw.split(",") if x.strip() != ""})
    return list(range(0, POSITION_LIMIT + 1, step))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--holds",
        default=None,
        help="Comma-separated list of hold values. Default: range(0, 81, --step).",
    )
    parser.add_argument(
        "--reservoirs",
        default=None,
        help="Comma-separated list of reservoir values. Default: range(0, 81, --step).",
    )
    parser.add_argument(
        "--step",
        type=int,
        default=DEFAULT_STEP,
        help=f"Step size for auto-generated hold/reservoir lists. Default: {DEFAULT_STEP}.",
    )
    parser.add_argument(
        "--output-dir",
        default="grid/hold_reservoir",
        help="Directory to write generated bot files into. Default: grid/hold_reservoir.",
    )
    parser.add_argument(
        "--include-anchors",
        action="store_true",
        help="Also include the current round1bot.py baseline (hold=77, reservoir=3).",
    )
    parser.add_argument(
        "--include-pure-hold",
        action="store_true",
        help="Keep reservoir=0 cells (pure buy-and-hold baseline for each hold level).",
    )
    parser.add_argument(
        "--full-capacity",
        action="store_true",
        help=(
            "Only emit cells where hold + reservoir == position limit (no idle "
            "capacity). When set, --reservoirs is ignored and reservoir is derived "
            "as (limit - hold) for each hold."
        ),
    )
    return parser.parse_args()


BOT_TEMPLATE = dedent(
    '''\
    #!/usr/bin/env python3
    """
    Pepper hold/reservoir sweep cell: HOLD={hold}, RESERVOIR={reservoir}.

    Auto-generated by scripts/generate_hold_reservoir_grid.py — do not edit by
    hand; regenerate instead.
    """
    from __future__ import annotations

    import json
    import math
    from dataclasses import dataclass, field
    from typing import Dict, List, Optional, Tuple

    try:
        from datamodel import Order, OrderDepth, TradingState
    except ImportError:
        @dataclass
        class Order:
            symbol: str
            price: int
            quantity: int

        @dataclass
        class OrderDepth:
            buy_orders: Dict[int, int] = field(default_factory=dict)
            sell_orders: Dict[int, int] = field(default_factory=dict)

        @dataclass
        class TradingState:
            traderData: str = ""
            timestamp: int = 0
            order_depths: Dict[str, OrderDepth] = field(default_factory=dict)
            position: Dict[str, int] = field(default_factory=dict)


    POSITION_LIMITS: Dict[str, int] = {{
        "ASH_COATED_OSMIUM": 80,
        "INTARIAN_PEPPER_ROOT": 80,
    }}

    OSMIUM_FAIR_VALUE = 10_000
    OSMIUM_MAX_BID = 9_999
    OSMIUM_MIN_ASK = 10_001
    OSMIUM_QUOTE_SIZE = 80

    # --- Pepper hold / reservoir cell --------------------------------------
    PEPPER_HOLD = {hold}                 # permanent long floor (drift capture)
    PEPPER_RESERVOIR = {reservoir}       # extra capacity used for MM on top of the hold
    PEPPER_MAX_POSITION = PEPPER_HOLD + PEPPER_RESERVOIR
    # -----------------------------------------------------------------------

    PEPPER_SLOPE = 0.001                 # mean +1 per 1000 timestamp units
    PEPPER_MM_OFFSET = 2                 # penny2-style offset from best quote
    PEPPER_EDGE_OFFSET = 3               # widen one extra tick at the band edges


    @dataclass
    class OrderBuilder:
        product: str
        position: int
        limit: int
        orders: List[Order] = field(default_factory=list)
        buy_used: int = 0
        sell_used: int = 0

        @property
        def buy_capacity(self) -> int:
            return max(0, self.limit - self.position - self.buy_used)

        @property
        def sell_capacity(self) -> int:
            return max(0, self.limit + self.position - self.sell_used)

        def add_buy(self, price: int, quantity: int) -> None:
            quantity = min(quantity, self.buy_capacity)
            if quantity > 0:
                self.orders.append(Order(self.product, int(price), int(quantity)))
                self.buy_used += quantity

        def add_sell(self, price: int, quantity: int) -> None:
            quantity = min(quantity, self.sell_capacity)
            if quantity > 0:
                self.orders.append(Order(self.product, int(price), int(-quantity)))
                self.sell_used += quantity


    def best_bid_ask(order_depth: OrderDepth) -> Optional[Tuple[int, int]]:
        if not order_depth.buy_orders or not order_depth.sell_orders:
            return None
        return max(order_depth.buy_orders), min(order_depth.sell_orders)


    class Trader:
        def run(self, state: TradingState):
            result: Dict[str, List[Order]] = {{}}
            saved = {{}}
            if state.traderData:
                try:
                    saved = json.loads(state.traderData)
                except json.JSONDecodeError:
                    pass

            for product, order_depth in state.order_depths.items():
                position = state.position.get(product, 0)
                limit = POSITION_LIMITS.get(product, 80)
                builder = OrderBuilder(product, position, limit)

                if product == "ASH_COATED_OSMIUM":
                    for ask_price in sorted(order_depth.sell_orders.keys()):
                        if ask_price >= OSMIUM_FAIR_VALUE:
                            break
                        builder.add_buy(ask_price, abs(order_depth.sell_orders[ask_price]))

                    for bid_price in sorted(order_depth.buy_orders.keys(), reverse=True):
                        if bid_price <= OSMIUM_FAIR_VALUE:
                            break
                        builder.add_sell(bid_price, abs(order_depth.buy_orders[bid_price]))

                    bba = best_bid_ask(order_depth)
                    if bba:
                        bot_bid, bot_ask = bba
                        bid_price = min(bot_bid + 1, OSMIUM_MAX_BID)
                        ask_price = max(bot_ask - 1, OSMIUM_MIN_ASK)
                    else:
                        bid_price = OSMIUM_MAX_BID
                        ask_price = OSMIUM_MIN_ASK

                    builder.add_buy(bid_price, OSMIUM_QUOTE_SIZE)
                    builder.add_sell(ask_price, OSMIUM_QUOTE_SIZE)

                elif product == "INTARIAN_PEPPER_ROOT":
                    # Phase 1: ramp up to the hold floor as quickly as possible.
                    if position < PEPPER_HOLD and order_depth.sell_orders:
                        deficit = PEPPER_HOLD - position
                        builder.add_buy(min(order_depth.sell_orders), deficit)
                    elif position < PEPPER_HOLD and order_depth.buy_orders:
                        deficit = PEPPER_HOLD - position
                        builder.add_buy(max(order_depth.buy_orders) + 1, deficit)

                    # Phase 2: MM with the reservoir on top of the hold.
                    if PEPPER_RESERVOIR > 0:
                        bba = best_bid_ask(order_depth)
                        if bba:
                            bot_bid, bot_ask = bba
                            mid = (bot_bid + bot_ask) / 2
                            timestamp = state.timestamp

                            # Rolling fair-value estimate: running mean of (mid - slope*t).
                            n = saved.get("pepper_n", 0) + 1
                            s = saved.get("pepper_sum", 0.0)
                            s += mid - PEPPER_SLOPE * timestamp
                            saved["pepper_n"] = n
                            saved["pepper_sum"] = s
                            intercept = s / n
                            fair_value = intercept + PEPPER_SLOPE * timestamp

                            max_bid = math.ceil(fair_value) - 1
                            min_ask = math.floor(fair_value) + 1

                            bid_offset = (
                                PEPPER_EDGE_OFFSET
                                if position <= PEPPER_HOLD + 1
                                else PEPPER_MM_OFFSET
                            )
                            ask_offset = (
                                PEPPER_EDGE_OFFSET
                                if position >= PEPPER_MAX_POSITION - 1
                                else PEPPER_MM_OFFSET
                            )

                            bid_price = min(bot_bid + bid_offset, max_bid)
                            ask_price = max(bot_ask - ask_offset, min_ask)

                            # Buy only while we're below the top of the band.
                            buy_room = max(0, PEPPER_MAX_POSITION - position)
                            if buy_room > 0:
                                builder.add_buy(bid_price, min(PEPPER_RESERVOIR, buy_room))

                            # Sell only above the hold floor — never dip into the core.
                            sell_room = max(0, position - PEPPER_HOLD)
                            if sell_room > 0:
                                builder.add_sell(ask_price, min(PEPPER_RESERVOIR, sell_room))

                result[product] = builder.orders

            return result, 0, json.dumps(saved)
    '''
)


def build_grid(
    holds: list[int],
    reservoirs: list[int],
    include_pure_hold: bool,
    include_anchors: bool,
    full_capacity: bool,
) -> list[tuple[int, int]]:
    cells: set[tuple[int, int]] = set()

    if full_capacity:
        for h in holds:
            if h < 0 or h > POSITION_LIMIT:
                continue
            r = POSITION_LIMIT - h
            if r == 0 and not include_pure_hold:
                continue
            if h == 0 and r == 0:
                continue
            cells.add((h, r))
    else:
        for h in holds:
            for r in reservoirs:
                if h < 0 or r < 0:
                    continue
                if h + r > POSITION_LIMIT:
                    continue
                if r == 0 and not include_pure_hold:
                    continue
                if h == 0 and r == 0:
                    continue
                cells.add((h, r))

    if include_anchors:
        anchor = (77, 3)
        if anchor[0] + anchor[1] <= POSITION_LIMIT:
            cells.add(anchor)

    return sorted(cells)


def render_bot(hold: int, reservoir: int) -> str:
    return BOT_TEMPLATE.format(hold=hold, reservoir=reservoir)


def main() -> None:
    args = parse_args()
    holds = parse_values(args.holds, args.step)
    reservoirs = parse_values(args.reservoirs, args.step)

    cells = build_grid(
        holds,
        reservoirs,
        args.include_pure_hold,
        args.include_anchors,
        args.full_capacity,
    )
    if not cells:
        raise SystemExit("No valid (hold, reservoir) cells given your inputs.")

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    manifest_rows: list[dict[str, object]] = []
    for hold, reservoir in cells:
        file_name = f"h{hold:02d}_r{reservoir:02d}.py"
        file_path = output_dir / file_name
        file_path.write_text(render_bot(hold, reservoir))
        manifest_rows.append(
            {
                "file": file_name,
                "hold": hold,
                "reservoir": reservoir,
                "max_position": hold + reservoir,
                "unused_capacity": POSITION_LIMIT - hold - reservoir,
            }
        )

    manifest_path = output_dir / "manifest.csv"
    with manifest_path.open("w", newline="") as fh:
        writer = csv.DictWriter(
            fh,
            fieldnames=["file", "hold", "reservoir", "max_position", "unused_capacity"],
        )
        writer.writeheader()
        writer.writerows(manifest_rows)

    print(f"Wrote {len(cells)} bot files to {output_dir.resolve()}")
    print(f"Manifest: {manifest_path.resolve()}")
    print()
    print(f"{'file':<22} {'hold':>5} {'reserve':>8} {'max_pos':>8} {'unused':>7}")
    print("-" * 55)
    for row in manifest_rows:
        print(
            f"{row['file']:<22} {row['hold']:>5} {row['reservoir']:>8} "
            f"{row['max_position']:>8} {row['unused_capacity']:>7}"
        )


if __name__ == "__main__":
    main()
